with-expecter: true
dir: "internal/repository/mocks"
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/benx421/payment-gateway/bank/internal/repository:
    interfaces:
      AccountRepository:
      TransactionRepository:
