// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra63PbuBH/VzDodSaZoSzq5UT6luTaq+fS1uO7y5fY1UDkSsSZBHgAKEf16H/vAOAL",
	"FPRw/Lj6G1/YXez+9gne44hnOWfAlMSze5wTQTJQIMzdh0IlXND/EkU5u4j1oxhkJGiuH+CZ+wG6+BG9",
	"WXKREYVIoZL5dRGGo6goaGyu4C0OMNXLcqISHGBGMsAzTDpcAizgj4IKiPFMiQICLKMEMmLlUwqEpvEf",
	"w+Jr2JuS3vLm/v22V1+PT7geDLc/4ACrTa5FkEpQtsLbbYA/kVwVAny7LV+19xmR/NRtRjXhEzeoaT/9",
	"/i5iyHKugEWbn2FzVQvS3exvjP5RALqFDVpygWi1TCEtPEgl0ZuMfEPDyQRFCRGy3nYCJAbRbLzFsfcz",
	"bA5uPyPfPgNbqQTPhpNJgDPKqvuBbzdXsCxY7DOWfdO2lYDlqbYSFdkTTaVJP7Wptpq3zDmTYJzxI4mv",
	"rOb1XcSZNoa+JHme0sh4T/93qTd/35LyBwFLPMN/6TeO3rdvZf9vQnBxVTKxLF0lfiEpja1zc4EWhaQM",
	"pEQpX9EIgV6NNaSY1gNJDbmXE65iiySINYhGnn9x9XdesPjlRLkCyQsRAWJcoaXhvQ3wJdlkwFTbx15K",
	"M7JYLmlEtbtqJEvjLOX6nchek9KgFjwHoajFHMl4YaWFbyTLU8Cz6XQ6DbB1KTzDlKnzcYNeyhSswFjB",
	"CetzGjtUzNv5ZBLC+3EY9mA4XfTGg3jcI+8G573x+Px8MhmPwzAMdz0jwJEAoiCeEyNaLUtMFPQUzcC7",
	"phBChyBXjN9++dH3MXzLqQD5IAZSEVUYrQErMjz7qi0s+BpifOMLXU1g+bqrq5pcUNmgtQNHPkcbDSO+",
	"+B0ihZuE9vqMbOXeIarT4gk0BwdoPiNydlFQ8TyOgtaOgwdDor01LwwMSjp+X6eTfYjolHvmOaIMRaZg",
	"DI4iJqOMZloPAx96IiLiOSuyBQhftSViZF+iN5+LhKG1zUYQv21zxuPJaBgOJoPB8P0oHJ2fa7ZNGTGY",
	"ulXEKGgn7uvr+H4wCgZTXwoOcLRe7xFsDYIuy/CtBSvAkWkwHLlijB0pdoUYBWO/CMbVN/OMM72whcDB",
	"0DAo1Ts8puuSzgaIcMgMw+GkRWgYTqctUsNwON6ltoPbxoxWZx2xXe41fvfDtI5ZjwMoepMVUqGMqChB",
	"jkO9fTR2fZHvSHOkOCq91MHKQ6Lk8/c/R9LSUdPZuvtJLVcq7e0TxJt2Stnb3CmObAPgmOnEvNOx0vM0",
	"cfuzxjHzfOH0gHG+C9NrTuPXCmifokx5/YnH0M7ilJnsM9exzvSM5a0JdtVdk5d1RLRFmv26qcfnth7X",
	"UJWSstWcNu3x/Na0x66UjKu5bSm6bxoG7nOSCiDxZl5I+7K8rQuR5pE2nfPA4h4aKM0zKo0XNiWGI5Fd",
	"4DxqX9OyR5vb5uzGk+DcbmYHk1A1lUc7ImOybYAzkJKswC3XPqwJTckiBbQgKWERICpRqptZlRBWzTQg",
	"RrUNDyPJitUw8wHpH0BSlezf2m6tmJgVGgMFq66Plo0lGZ8EVTB+jtL/Werzh5TaJfS6/AUsT+E/2k/y",
	"gf3BrhlrLzpqu2YPgRvID9b6bTF9ZrdBfq/Rn69n21VFGWF8jq9f7bA3D09gP8R7KD7IeB1rVBId7r4a",
	"Lru61xQpW/LdzPlrQqWOOQRlPLpFC8Ju0YfLCzNcze2gCK2IgjuyQcbLhM2xCqSibHV2zS4UkjQrUqJA",
	"Ip1h3JI2qOqkwGTkABEWl3UM0uY3H8mza2YkMUJ8rITIBV/TGCRaEEkjtCxYpL8mKVUbneK1ELWUy5Tf",
	"SXRHVcILhQSQFGWcwQYpQZgkUcXnmn1IU3T5719+RcDinFNd15XqRoShzlwY2bnx2TWb/BXxZTNmvqNp",
	"igRhMc/SDVoSmhrmaBKGduanmWlW9YqErAFRpk0CMdIKY9EGLUDdATA0CMPeMAzDTK/TmKDKQM9o459a",
	"Lx8uL7SdQUhru8FZeBZqgPEcGMkpnuHRWXg2svVLYgDfJzntrwd9xyb2TIVLT8F7mZIIXAuihKcx4gyR",
	"KDLVsCkVzrDhK+pDGF8rbyRpjm6++tNl80l/zzHA9sZ6BEj1kcebJxtZHpg+bF0vVKKA7uh7GIZPJol/",
	"8ukZorqlbjlk0yAYW2l8TGqp+61pvVkyPL6kOy7eBnhyCit3/G4GvUWWEbGpoeKBmcY9WWmouBvFN5qA",
	"H8z9+85R3VYLtwJjEReiP4F6HD67R48WmP9fmKgH/eNwfNxM9amEa6GfQHXME4MiNJWnWaiM+QcCTdXY",
	"EpQLWFNeyHRTc4TYoOEMlf33vnnJviD0qZ5nvILw05kqvXDg6c7hPfCqTPW4YPP4oFEhpuPBFRwro3uB",
	"2L+vD7oPhofvRU5zPv+sIeEB1nqyMFAqzhMAvBq3td0Bzy+PwElFOK5KOJ+7l9/sc/SraiD2CvzcHUG+",
	"sJt3Wm7vYbExy5/s5JUUtRtWWCst7YNa/776MeKga38nVup/OZ7VsU+2z5O5ddmD7Xq1T9O6dTuYzFkE",
	"qe6ePJ3DApZcZ4/DnvzFjmtfgR+3Z9Uv7MXOBMX3Ywynf7oHGxn25WhjZYssO0g85LB2UImfUZ+dUahH",
	"o/YLVE5Z3J2W76IEotvWHkuxbww1+xOQBbNL+TOPSIpiWEPKczPBsN/iABcixTOcKJXP+v1Uf5dwqWbv",
	"371/Z7Bdcrr3y0pYXMrbDDiaf8hK6baB9/zYdd9mPtOsd4v+XTJlu1hXDT4aVd2wu9rtZHTU8RIwMNpd",
	"fdUdKzUryqC2vdn+LwAA//9b+JmPXCoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
